options:
  training-operator-image:
    default: docker.io/charmedkubeflow/training-operator:1.9.3-fa7483b-20260909084111
    description: |
      Container image to be used by the training-operator workload.
    type: string
