---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ app_name }}
  name: {{ namespace }}-{{ app_name }}-charm
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - tfjobs
      - mxjobs
      - pytorchjobs
      - xgboostjobs
      - tfjobs/status
      - pytorchjobs/status
      - mxjobs/status
      - xgboostjobs/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - scheduling.volcano.sh
    resources:
      - podgroups
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ app_name }}
  name: {{ namespace }}-{{ app_name }}-charm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ namespace }}-{{ app_name }}-charm
subjects:
- kind: ServiceAccount
  name: {{ app_name }}
  namespace: {{ namespace }}
