name: Publish

on:
  push:
    branches:
      - main
      - track/**
  pull_request:
    types:
      - opened
      - edited
    branches:
      - branch/**
jobs:
  charm:
    name: Publish Charm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: Update to @main when https://github.com/canonical/charmhub-upload-action/pull/3 merged
    - uses: canonical/charmhub-upload-action@branch/upload-charm-revisions
      with:
        credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
