name: Release to CharmHub

on:
  workflow_dispatch:

jobs:
  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v49.0.1
    with:
      cache: true
      charmcraft-snap-channel: 3.x/stable

  release:
    name: Release to CharmHub
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v49.0.1
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      track: latest
      path-to-charm-directory: .
    secrets:
      charmhub-token: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
    permissions:
      actions: read
      contents: write
