name: Run weekly tests

on:
  schedule:
    - cron: '0 8 * * TUE'

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/integrate.yaml
    secrets:
      charmcraft-credentials: '${{ secrets.CHARMCRAFT_CREDENTIALS }}'
